//! Native registers everything; WASM cfg-gates out particle/smoke effects
//! (bevy_hanabi isn't wasm-friendly), so on WASM the corresponding component
//! types / setup fns are dead code. Also: web-sys keeps deprecating audio/
//! video constraint setters, and several cfg-gated paths leave unused
//! imports/mut/vars. Blanket-allow these only on wasm32 so CI's
//! `-D warnings` doesn't fail the WASM deploy on items intentionally unused
//! for that target. Native still catches everything.
#![cfg_attr(target_arch = "wasm32", allow(
    dead_code,
    deprecated,
    unused_imports,
    unused_mut,
    unused_variables,
))]

pub mod accessibility;
pub mod achievements;
pub mod ai_driver;
pub mod ai_path;
pub mod airtime;
pub mod arrow;
pub mod ascii_logo;
pub mod asset_attribution;
pub mod asset_browser;
pub mod asset_manifest;
pub mod assists;
pub mod audio;
pub mod banners;
pub mod benchmark;
pub mod billboards;
pub mod biome_canyon;
pub mod birds_flock;
pub mod buildings;
pub mod biome_desert;
pub mod bloom_pp;
pub mod boats;
pub mod boost;
pub mod breadcrumbs;
pub mod camera;
pub mod camera_modes;
pub mod campfires;
pub mod career;
pub mod challenges;
pub mod changelog;
pub mod chassis_underglow;
pub mod chrome_polish;
pub mod climb_assist;
pub mod collectibles;
pub mod combo;
pub mod compass;
pub mod compass_hud;
pub mod confetti;
pub mod config;
pub mod course;
pub mod crash_audio;
pub mod credits;
pub mod daily;
pub mod damage;
pub mod damage_visual;
pub mod decals;
pub mod demo_mode;
pub mod demolition;
pub mod diff_lock;
pub mod distant_thunder;
pub mod drift_meter;
pub mod drive_mode;
pub mod explore;
pub mod drone;
pub mod engine_bay;
pub mod engine_pro;
pub mod engine_torque;
pub mod exhaust;
pub mod exhaust_smoke;
pub mod events;
pub mod fast_travel_menu;
pub mod fence_posts;
pub mod fish;
pub mod font_assets;
pub mod fireworks;
pub mod fog_horn;
pub mod fuel;
pub mod garage;
pub mod gas_stations;
pub mod gauge;
pub mod custom_map_loader;
pub use custom_map_loader::{CustomGlbRequest, CustomGlbTerrainMarker, CustomMapLoaderPlugin};
pub mod gpx_overlay;
pub use gpx_overlay::{GpxOverlayMarker, GpxOverlayPlugin, GpxOverlayRequest};
pub mod glb_loader;
pub mod godrays;
pub mod graphics_quality;
pub mod platform_storage;
pub mod grass_tufts;
pub mod ground_ruts;
pub mod headless;
pub mod heat_haze;
pub mod headlights;
pub mod heightmap_loader;
pub mod help;
pub mod hillclimb;
pub mod hillclimb_tiers;
pub use hillclimb_tiers::{HillclimbTiersPlugin, HillclimbTiersState, CHANNEL_LEADERBOARD};
pub mod hillclimb_track;
pub mod horn;
pub mod hud;
pub mod impact_flash;
pub mod input_remap;
pub mod interior_3d;
pub mod intro_video;
pub mod jump_meter;
pub mod landmarks;
pub mod license_plate;
pub mod livery;
pub mod loading_screen;
pub mod low_fuel_warning;
pub mod low_range;
pub mod map_select;
pub mod notifications;
pub mod paint_shop;
pub mod radar_pickups;
pub mod ramp_arrows;
pub mod maps;
pub mod markers;
pub mod medals;
pub mod menu;
pub mod minimap;
pub mod minimap_zoom;
pub mod mixer;
pub mod mountain_range;
pub mod night_glow;
pub mod nitro_gauge;
pub mod mud;
pub mod mud_depth;
pub mod mud_puddles;
pub mod music;
pub mod obstacles;
pub mod particles;
pub mod perf;
pub mod photomode;
pub mod pins;
pub mod progression;
pub mod pursuit;
pub mod race;
pub mod ramps;
pub mod recovery;
pub mod rock_crawl_trail;
pub use rock_crawl_trail::{RockCrawlLeaderboard, RockCrawlTrailPlugin, RockCrawlTrailState};
pub mod trail_rides;
pub use trail_rides::{
    ActiveTrailSession, TrailEntry, TrailLeaderboard, TrailManifest,
    TrailRideRequest, TrailRidesPlugin,
};
pub mod mission_select;
pub use mission_select::{MissionSelectOpen, MissionSelectPlugin};
pub mod obstacle_course;
pub use obstacle_course::{
    ObstacleCourseLeaderboard, ObstacleCoursePlugin, ObstacleCourseState, ObstacleCourseLayout,
};
pub mod rock_garden;
pub mod roof_rack;
pub mod repair;
pub mod replay;
pub mod rival;
pub mod rival_hud;
pub mod route;
pub mod save;
pub mod scatter;
pub mod screenshot;
pub mod season;
pub mod session_summary;
pub mod settings;
pub mod shake;
pub mod skidmarks;
pub mod sky;
pub mod snow;
pub mod spawn_points;
pub mod speedlines;
pub mod splash_particles;
pub mod speedtrap;
pub mod stars;
pub mod stats_screen;
pub mod storm;
pub mod stunt_score;
pub mod surfaces;
pub mod suspension_arms;
pub mod terrain;
pub mod terrain_lod;
pub mod terrain_normal_map;
pub mod terrain_splatmap;
pub mod theme;
pub mod time_trial;
pub mod tire_pressure;
pub mod tire_smoke;
pub mod tire_squash;
pub mod traffic;
pub mod trailers;
pub mod trail;
pub mod trampolines;
pub mod transition;
pub mod tree_variants;
pub mod trial;
pub mod truck_bed_cargo;
pub mod tutorial;
pub mod ufo;
pub mod unlocks;
pub mod variants;
pub mod vehicle;
pub mod vehicle_detail;
pub mod vehicle_dirt;
// Sprint 47 — three new procedural vehicles
pub mod vehicle_highland;
pub mod vehicle_dune_skipper;
pub mod vehicle_hauler;
// Sprint 60 — procedural PBR maps for all four vehicles
pub mod vehicle_textures;
pub use vehicle_textures::{VehicleTexturesPlugin, VehicleTextureSet};
pub mod water;
pub mod water_reflective;
pub mod weather_clouds;
pub mod wheel_detail;
pub mod wheel_rims;
pub mod wheel_well;
pub mod winch;
pub mod wheelie;
pub mod wildlife;
pub mod wind;
pub mod world_audio;
pub mod xp;

pub mod engine_audio_layered;
pub mod fuel_consumption_real;
pub mod spectate;
pub mod transfer_case;
pub mod transmission;
pub mod winch_cable_physics;
pub mod vehicle_mods;
pub use vehicle_mods::{VehicleModsPlugin, VehicleModsState, TireSize, BumperKind};
pub use engine_audio_layered::EngineAudioLayeredPlugin;
pub use fuel_consumption_real::FuelConsumptionRealPlugin;
pub use transfer_case::TransferCasePlugin;
pub use transmission::TransmissionPlugin;
pub use winch_cable_physics::WinchCablePhysicsPlugin;

pub mod buddy_recovery;
pub use buddy_recovery::{BuddyRecoveryPlugin, RecoveryState as BuddyRecoveryState};

pub mod multiplayer;
pub use multiplayer::MultiplayerPlugin;

pub mod voice;
pub use voice::VoicePlugin;

pub mod hdr_skybox;
pub mod photo_hud;
pub mod photoreal_rocks;
pub mod terrain_decals;
pub mod terrain_grass_blades;
pub use hdr_skybox::HdrSkyboxPlugin;
pub use photo_hud::PhotoHudPlugin;
pub use photoreal_rocks::PhotorealRocksPlugin;
pub use terrain_decals::TerrainDecalsPlugin;
pub use terrain_grass_blades::TerrainGrassBladesPlugin;

pub mod terrain_pbr;
pub use terrain_pbr::{TerrainPbrAssets, TerrainPbrPlugin, TriplanarTerrainExt, TriplanarTerrainMaterial};

pub mod post_fx;
pub use post_fx::PostFxPlugin;

// ---- Monetization stack -----------------------------------------------------
// Brand-pack-driven sponsor scatter, player wallet/inventory, and ad SDK bridge.
// All four are additive plugins; none mutate the base game's behaviour unless
// explicitly wired (e.g. fuel.rs emitting AdRequest::Rewarded { slot: "refuel" }).
pub mod brand_pack;
pub mod wallet;
pub mod ad_sdk_bridge;
pub mod sponsor_scatter;
pub use brand_pack::{ActiveBrandPack, BrandPack, BrandPackPlugin};
pub use wallet::{Inventory, Wallet, WalletPlugin};
pub use ad_sdk_bridge::{AdRequest, AdResult, AdSdkPlugin};
pub use sponsor_scatter::{SponsorAnalytics, SponsorBillboard, SponsorScatterPlugin};

pub use audio::AudioPlugin;
pub use camera::CameraPlugin;
pub use compass::CompassPlugin;
pub use damage::DamagePlugin;
pub use events::{EventLog, EventLogPlugin, GameEvent};
pub use help::HelpPlugin;
pub use hud::{HudPlugin, SessionStats};
pub use menu::MenuPlugin;
pub use minimap::MinimapPlugin;
pub use particles::DustPlugin;
pub use perf::PerfPlugin;
pub use save::SavePlugin;
pub use scatter::ScatterPlugin;
pub use settings::SettingsPlugin;
pub use sky::SkyPlugin;
pub use stats_screen::StatsScreenPlugin;
pub use terrain::TerrainPlugin;
pub use vehicle::{Chassis, DefaultSkin, DriveInput, VehiclePlugin, VehiclePluginHeadless, VehicleRoot, Wheel};
pub use banners::BannersPlugin;
pub use markers::MarkersPlugin;
pub use obstacles::ObstaclesPlugin;
pub use route::RoutePlugin;
pub use variants::VariantsPlugin;
pub use boost::BoostPlugin;
pub use collectibles::CollectiblesPlugin;
pub use drone::DronePlugin;
pub use exhaust::ExhaustPlugin;
pub use screenshot::ScreenshotPlugin;
pub use arrow::ArrowPlugin;
pub use course::{CoursePlugin, CourseState};
pub use pins::PinsPlugin;
pub use trail::TrailPlugin;
pub use tutorial::TutorialPlugin;
pub use engine_pro::EngineProPlugin;
pub use mixer::MixerPlugin;
pub use music::MusicPlugin;
pub use surfaces::SurfacesPlugin;
pub use world_audio::WorldAudioPlugin;
pub use water::WaterPlugin;
pub use livery::LiveryPlugin;
pub use mud::MudPlugin;
pub use recovery::RecoveryPlugin;
pub use repair::RepairPlugin;
pub use trial::TrialPlugin;
pub use achievements::AchievementToastPlugin;
pub use horn::HornPlugin;
pub use photomode::PhotoModePlugin;
pub use replay::ReplayPlugin;
pub use wind::WindPlugin;
pub use breadcrumbs::BreadcrumbsPlugin;
pub use fuel::FuelPlugin;
pub use headlights::HeadlightsPlugin;
pub use ramps::RampsPlugin;
pub use skidmarks::SkidmarksPlugin;
pub use airtime::AirtimePlugin;
pub use gauge::GaugePlugin;
pub use speedtrap::SpeedTrapPlugin;
pub use trampolines::TrampolinesPlugin;
pub use wheelie::WheelieCounterPlugin;
pub use confetti::ConfettiPlugin;
pub use shake::ShakePlugin;
pub use speedlines::SpeedLinesPlugin;
pub use stars::StarsPlugin;
pub use xp::XpPlugin;
pub use ai_driver::{AiDriver, AiDriverPlugin};
pub use ai_path::{AiPathPlugin, PathFollower, RacePath};
pub use race::{RaceEntry, RacePhase, RacePlugin, RaceState};
pub use rival::{Rival, RivalChassis, RivalPlugin, RivalWheel};
pub use rival_hud::RivalHudPlugin;
pub use career::{CareerObjective, CareerPlugin, CareerState, ObjectiveKind};
pub use daily::{DailyChallenge, DailyKind, DailyPlugin, DailyState};
pub use medals::{Medal, MedalChallenge, MedalsPlugin, MedalsState};
pub use progression::{ProgressionPlugin, ProgressionState};
pub use unlocks::{UnlockState, Unlockable, UnlocksPlugin};
pub use biome_canyon::BiomeCanyonPlugin;
pub use biome_desert::BiomeDesertPlugin;
pub use map_select::MapSelectPlugin;
pub use maps::{ActiveMap, MapInfo, MapKind, MapsPlugin};
pub use transition::{TransitionDirection, TransitionPlugin, TransitionRequest, TransitionState};
pub use config::{ConfigPlugin, PersistedConfig};
pub use credits::CreditsPlugin;
pub use font_assets::{FontAssets, FontAssetsPlugin};
pub use loading_screen::LoadingScreenPlugin;
pub use theme::ThemePlugin;
pub use accessibility::{AccessibilityPlugin, AccessibilityState};
pub use benchmark::{BenchmarkPlugin, BenchmarkState};
pub use changelog::ChangelogPlugin;
pub use demo_mode::{DemoModePlugin, DemoModeState};
pub use input_remap::{InputRemapPlugin, KeyBindings};
pub use bloom_pp::{BloomPpPlugin, BloomPpState};
pub use graphics_quality::{GraphicsQuality, GraphicsQualityPlugin};
pub use decals::DecalsPlugin;
pub use godrays::GodraysPlugin;
pub use storm::{StormPlugin, StormState};
pub use vehicle_dirt::{DirtState, VehicleDirtPlugin};
pub use challenges::{ChallengesPlugin, ChallengesState};
pub use demolition::{DemolitionPlugin, DemolitionState};
pub use explore::{ExplorePlugin, ExploreState};
pub use pursuit::{PursuitPlugin, PursuitState};
pub use time_trial::{TimeTrialPlugin, TimeTrialState};
pub use ascii_logo::AsciiLogoPlugin;
pub use birds_flock::BirdsFlockPlugin;
pub use buildings::BuildingsPlugin;
pub use intro_video::{IntroVideoPlugin, IntroVideoState};
pub use traffic::{TrafficPlugin, TrafficState};
pub use exhaust_smoke::ExhaustSmokePlugin;
pub use landmarks::LandmarksPlugin;
pub use minimap_zoom::{MinimapZoomPlugin, MinimapZoomState};
pub use season::{Season, SeasonPlugin, SeasonState};
pub use weather_clouds::WeatherCloudsPlugin;
pub use assists::{AssistsPlugin, AssistsState};
pub use climb_assist::{ClimbAssistPlugin, ClimbAssistState};
pub use fireworks::FireworksPlugin;
pub use garage::{GaragePlugin, GarageState};
pub use spawn_points::{SpawnPointsPlugin, SpawnPointsState};
pub use campfires::CampfiresPlugin;
pub use combo::{ComboPlugin, ComboState};
pub use jump_meter::{JumpMeterPlugin, JumpMeterState};
pub use mountain_range::MountainRangePlugin;
pub use wildlife::WildlifePlugin;
pub use compass_hud::CompassHudPlugin;
pub use damage_visual::{DamageVisualPlugin, DamageVisualState};
pub use fast_travel_menu::FastTravelMenuPlugin;
pub use snow::SnowPlugin;
pub use ufo::{UfoPlugin, UfoState};
pub use billboards::BillboardsPlugin;
pub use gas_stations::GasStationsPlugin;
pub use impact_flash::ImpactFlashPlugin;
pub use low_fuel_warning::LowFuelWarningPlugin;
pub use tire_smoke::TireSmokePlugin;
pub use boats::BoatsPlugin;
pub use crash_audio::CrashAudioPlugin;
pub use distant_thunder::DistantThunderPlugin;
pub use fish::FishPlugin;
pub use fog_horn::FogHornPlugin;
pub use license_plate::LicensePlatePlugin;
pub use notifications::{Notification, NotificationQueue, NotificationsPlugin};
pub use paint_shop::{PaintShopPlugin, PaintShopState};
pub use radar_pickups::RadarPickupsPlugin;
pub use session_summary::SessionSummaryPlugin;
pub use drift_meter::{DriftMeterPlugin, DriftMeterState};
pub use nitro_gauge::{NitroGaugePlugin, NitroGaugeState};
pub use ramp_arrows::RampArrowsPlugin;
pub use stunt_score::{StuntScorePlugin, StuntScoreState};
pub use trailers::{TrailerState, TrailersPlugin};
pub use camera_modes::{CameraMode, CameraModesPlugin, CameraModesState};
pub use chassis_underglow::ChassisUnderglowPlugin;
pub use suspension_arms::SuspensionArmsPlugin;
pub use vehicle_detail::VehicleDetailPlugin;
pub use wheel_detail::WheelDetailPlugin;
pub use ground_ruts::GroundRutsPlugin;
pub use mud_puddles::MudPuddlesPlugin;
pub use rock_garden::RockGardenPlugin;
pub use splash_particles::SplashParticlesPlugin;
pub use tire_squash::TireSquashPlugin;
pub use hillclimb::{HillclimbPhase, HillclimbPlugin, HillclimbState};
pub use hillclimb_track::{HillclimbFinishGate, HillclimbStartGate, HillclimbTrackPlugin};
pub use low_range::{LowRangePlugin, LowRangeState};
pub use tire_pressure::{TirePressurePlugin, TirePressureState};
pub use winch::{WinchPlugin, WinchState};
pub use diff_lock::{DiffLockPlugin, DiffLockState};
pub use drive_mode::{DriveModePlugin, DriveModeState};
pub use engine_bay::EngineBayPlugin;
pub use engine_torque::{EngineState, EngineTorquePlugin};
pub use interior_3d::Interior3dPlugin;
pub use fence_posts::FencePostsPlugin;
pub use grass_tufts::GrassTuftsPlugin;
pub use roof_rack::{RoofRackPlugin, RoofRackState};
pub use tree_variants::TreeVariantsPlugin;
pub use wheel_well::WheelWellPlugin;
pub use chrome_polish::ChromePolishPlugin;
pub use heat_haze::HeatHazePlugin;
pub use asset_attribution::AssetAttributionPlugin;
pub use asset_browser::AssetBrowserPlugin;
pub use asset_manifest::{AssetManifest, AssetManifestPlugin, MapEntry, ModEntry, VehicleClassEntry};
pub use glb_loader::{GlbLoaderPlugin, LoadedVehicleGlbs};
pub use heightmap_loader::{
    CustomHeightmapRequest, CustomTerrainMarker,
    HeightmapLoaderPlugin, LoadedHeightmaps, heightmap_to_mesh,
    CUSTOM_GRID, CUSTOM_MAX_HEIGHT, CUSTOM_WORLD_SIZE,
};
pub use mud_depth::MudDepthPlugin;
pub use terrain_lod::TerrainLodPlugin;
pub use terrain_normal_map::TerrainNormalMapPlugin;
pub use terrain_splatmap::TerrainSplatmapPlugin;
pub use water_reflective::WaterReflectivePlugin;
pub use night_glow::NightGlowPlugin;
pub use truck_bed_cargo::TruckBedCargoPlugin;
pub use wheel_rims::WheelRimsPlugin;
